Repository 1c-syntax/bsl-language-server, pull requests merged in 2019-10, with the labels that each got.

#411 Feature/fp diagnostics
  docs/diagnostics/UsingHardcodePath.md
  docs/en/diagnostics/UsingHardcodePath.md
  src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodePathDiagnostic.java
  src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingObjectNotAvailableUnixDiagnostic.java
  src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodePathDiagnosticTest.java
  src/test/resources/diagnostics/UsingHardcodePathDiagnostic.bsl
  src/test/resources/diagnostics/UsingObjectNotAvailableUnixDiagnostic.bsl
Labels: type/FP

#397 Исправление замечания сонара
  src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitTestSuites.java
Labels: sonarqube

#491 #67 UnusedLocalMethodDiagnostic
  docs/diagnostics/UnusedLocalMethod.md
  docs/en/diagnostics/UnusedLocalMethod.md
  src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalMethodDiagnostic.java
  src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalMethodDiagnostic_en.properties
  src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalMethodDiagnostic_ru.properties
  src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalMethodDiagnosticTest.java
  src/test/resources/diagnostics/UnusedLocalMethodDiagnostic.bsl
Labels: component/diagnostics
